services:
  booksystem:
    image: ${DOCKER_REGISTRY-}booksystem
    container_name: booksystem
    build:
      context: .
      dockerfile: BookSystem/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - booksystem.database
    networks:
      - app-network

  booksystem.database:
    image: 'bitnami/postgresql:latest'
    container_name: booksystem.database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./.containers/booksystem-db-data:/bitnami/postgresql
    networks:
      - app-network

networks:
  app-network:

volumes:
  booksystem-db-data: